Prof 1
PROF-Development/vite-react-template pull request #1
Opened 2024-04-23 11:55 UTC by GlebVas7

Установил ESLint  для предупреждения о проблемах в коде, Prettier для автоматического форматирования кода и изменения последовательности импортов, а такжe husky для проверки сообщения коммита

2024-04-23 14:16 UTC, Amer-On requested changes

2024-04-23 14:16 UTC, Amer-On commented on src/components/Footer.jsx
> +/*import React from 'react';*/
это хуки закомментили эти строчки?

2024-04-23 14:16 UTC, Amer-On commented on src/components/StaticPage.jsx
> +                                     // eslint-disable-next-line react/prop-types
не круто перед каждым пропсом прописывать игнор какой-то штуки. В чём тут проблематика?

2024-04-23 14:16 UTC, Amer-On commented on src/pages/HomePage.jsx
> +      <div>
этот див для чего добавил?

2024-04-23 14:18 UTC, GlebVas7 commented on src/components/Footer.jsx
> +/*import React from 'react';*/
нет, я коментил, потому что хук ругается на то, что это не использовано

2024-04-23 14:18 UTC, GlebVas7 commented on src/components/StaticPage.jsx
> +                                     // eslint-disable-next-line react/prop-types
это сайчас уберу, я тестил хуки, забыл убрать

2024-04-23 14:19 UTC, GlebVas7 commented on src/pages/HomePage.jsx
> +      <div>
это тоже тестил хуки, уберу

2024-04-25 11:05 UTC, Amer-On approved these changes
squash

2024-04-25 11:51 UTC, merged