PROF-2 прокидывание конфиги
PROF-Development/vite-react-template pull request #2
Opened 2024-04-24 14:02 UTC by vadim-221212

2024-04-24 14:05 UTC, vadim-221212 commented
Установил  js-yaml для считывания local.yaml , теперь local.yaml загружается и дает пользоваться во всем проекте своими данными .

2024-05-16 08:17 UTC, Amer-On requested changes
сделай файл config/defaults
там сделай объект config со значениями по умолчанию

пока что добавь туда просто DEBUG: false


сделай файл config/index.js

там сделай объект config
он должен строиться по следующему алгоритму:

берётся конфиг из default и перезаписывается значениями из yaml файла

в дальнейшем именно конфиг из index.js и будет использоваться везде

2024-05-16 08:17 UTC, Amer-On commented on vite.config.js
> +    yaml() // Плагин yaml добавлен в массив plugins
коммент не нужен

2024-05-16 08:17 UTC, Amer-On commented on src/config/loaders.js
> +  console.log('Конфигурация успешно загружена:', config);
добавь переменную DEBUG в конфиг со значением по умолчанию false

выводи это сообщение только если debug = true

2024-05-16 08:17 UTC, Amer-On commented on src/App.jsx
> +//import { loadConfig} from './config/loaders';
комментарии то убери

2024-05-16 08:17 UTC, Amer-On commented on src/config/loaders.js
> +export function getConfig() {
убери

2024-05-21 09:30 UTC, Amer-On requested changes

2024-05-21 09:30 UTC, Amer-On commented on src/config/loaders.js
> +export const config = {};
видно же, что абсолютно бесполезная переменная

2024-05-21 09:30 UTC, Amer-On commented on src/config/loaders.js
> +export function loadConfig() {
пусть функция возвращает, считанный конфиг, а не перезаписывает глобальную переменную

это же куда лучше, не думаешь?

2024-05-22 15:32 UTC, Amer-On approved these changes
squash and merge

2024-05-27 21:00 UTC, merged